- name: Add ClickHouse GPG key
  apt_key:
    url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key  
    state: present

- name: Add ClickHouse repository without GPG key
  apt_repository:
    repo: "deb https://packages.clickhouse.com/deb stable main"
    state: present

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install ClickHouse server and client
  apt:
    name:
      - clickhouse-server
      - clickhouse-client
    state: present

- name: Deploy ClickHouse configuration file clickhouse_config.xml
  template:
    src: "{{ clickhouse_config }}"
    dest: /etc/clickhouse-server/config.d/clickhouse_config.xml # may create variable insted of "clickhouse_config.xml" to name file (should have .xml extension)

- name: Deploy ClickHouse configuration file zookeeper_config.xml
  template:
    src: "{{ zookeeper_config }}"
    dest: /etc/clickhouse-server/config.d/zookeeper_config.xml  # may create variable insted of "zookeeper_config.xml" to name file (should have .xml extension)
  notify:
    - Restart ClickHouse server 

- name: Deploy ClickHouse configuration file for user user_config.xml 
  template:
    src: "{{ clickhouse_user_config }}"
    dest: /etc/clickhouse-server/users.d/user_config.xml # may create variable insted of "clickhouse_config.xml" to name file (should have .xml extension)


- name: Enable and start ClickHouse server
  service:
    name: clickhouse-server
    state: started
    enabled: yes

- name: Verify ClickHouse is running
  command: clickhouse-client --query "SELECT 1" --user={{ clickhouse_connect_user }} --password={{ clickhouse_connect_password }}
  register: clickhouse_check
  changed_when: false
  failed_when: "'1' not in clickhouse_check.stdout"

- name: Display ClickHouse status
  debug:
    msg: "ClickHouse server is running and responding correctly."
